name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main', 'dev']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint:fix
      - uses: autofix-ci/action@v1.3.1
        with:
          commit-message: 'chore: apply automated updates'
